'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ImpresionIndicadoresService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:resinplast:Indicadores:ImpresionIndicadores", ConfigurationName:="ImpresionIndicadoresService.IImpresionIndicadores")>  _
    Public Interface IImpresionIndicadores
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresSetUpIndividual", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresSetUpIndividual(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresSetUpTotal", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresSetUpTotal(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresSetUpConHeptacrom"& _ 
            "ia", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresSetUpConHeptacromia(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresSetUpSinHeptacrom"& _ 
            "iaIndividual", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresSetUpSinHeptacromiaIndividual(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresSetUpSinHeptacrom"& _ 
            "iaTotal", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresSetUpSinHeptacromiaTotal(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresMetrosIndividuale"& _ 
            "s", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresMetrosIndividuales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresMetrosRequest) As ImpresionIndicadoresService.ImpresionIndicadoresMetrosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresMetrosTotales", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresMetrosTotales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresMetrosRequest) As ImpresionIndicadoresService.ImpresionIndicadoresMetrosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresScrapIndividuales"& _ 
            "", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresScrapIndividuales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresScrapRequest) As ImpresionIndicadoresService.ImpresionIndicadoresScrapResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresScrapTotales", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresScrapTotales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresScrapRequest) As ImpresionIndicadoresService.ImpresionIndicadoresScrapResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresVelocidadIndividu"& _ 
            "ales", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresVelocidadIndividuales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadRequest) As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:ImpresionIndicadores:ListaIndicadoresVelocidadTotales", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListaIndicadoresVelocidadTotales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadRequest) As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BaseErrorEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private parametrosField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("Codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Parametros() As String
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
                Me.RaisePropertyChanged("Parametros")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ImpresionIndicadoresVelocidadEL)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ImpresionIndicadoresScrapEL)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ImpresionIndicadoresMetrosEL)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ImpresionIndicadoresSetUpEL)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BaseEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private flagEstadoField As Integer
        
        Private usuarioCreacionField As String
        
        Private fechaCreacionField As Date
        
        Private usuarioModificacionField As String
        
        Private fechaModificacionField As Date
        
        Private usuarioEliminacionField As String
        
        Private fechaEliminacionField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property FlagEstado() As Integer
            Get
                Return Me.flagEstadoField
            End Get
            Set
                Me.flagEstadoField = value
                Me.RaisePropertyChanged("FlagEstado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property UsuarioCreacion() As String
            Get
                Return Me.usuarioCreacionField
            End Get
            Set
                Me.usuarioCreacionField = value
                Me.RaisePropertyChanged("UsuarioCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property FechaCreacion() As Date
            Get
                Return Me.fechaCreacionField
            End Get
            Set
                Me.fechaCreacionField = value
                Me.RaisePropertyChanged("FechaCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property UsuarioModificacion() As String
            Get
                Return Me.usuarioModificacionField
            End Get
            Set
                Me.usuarioModificacionField = value
                Me.RaisePropertyChanged("UsuarioModificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property FechaModificacion() As Date
            Get
                Return Me.fechaModificacionField
            End Get
            Set
                Me.fechaModificacionField = value
                Me.RaisePropertyChanged("FechaModificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property UsuarioEliminacion() As String
            Get
                Return Me.usuarioEliminacionField
            End Get
            Set
                Me.usuarioEliminacionField = value
                Me.RaisePropertyChanged("UsuarioEliminacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property FechaEliminacion() As Date
            Get
                Return Me.fechaEliminacionField
            End Get
            Set
                Me.fechaEliminacionField = value
                Me.RaisePropertyChanged("FechaEliminacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ImpresionIndicadoresVelocidadEL
        Inherits BaseEL
        
        Private idRecursoField As String
        
        Private añoField As String
        
        Private mesField As String
        
        Private sumaMetrosField As Double
        
        Private sumaHorasField As Double
        
        Private velocidadTotalField As Double
        
        Private velocidadEfectivaField As Double
        
        Private velocidadObjetivoField As Double
        
        Private tipoRecursoField As String
        
        Private descripcionFechaField As String
        
        Private buscarFechaInicioField As Date
        
        Private buscarFechaFinField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdRecurso() As String
            Get
                Return Me.idRecursoField
            End Get
            Set
                Me.idRecursoField = value
                Me.RaisePropertyChanged("IdRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Año() As String
            Get
                Return Me.añoField
            End Get
            Set
                Me.añoField = value
                Me.RaisePropertyChanged("Año")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Mes() As String
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
                Me.RaisePropertyChanged("Mes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property SumaMetros() As Double
            Get
                Return Me.sumaMetrosField
            End Get
            Set
                Me.sumaMetrosField = value
                Me.RaisePropertyChanged("SumaMetros")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property SumaHoras() As Double
            Get
                Return Me.sumaHorasField
            End Get
            Set
                Me.sumaHorasField = value
                Me.RaisePropertyChanged("SumaHoras")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property VelocidadTotal() As Double
            Get
                Return Me.velocidadTotalField
            End Get
            Set
                Me.velocidadTotalField = value
                Me.RaisePropertyChanged("VelocidadTotal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property VelocidadEfectiva() As Double
            Get
                Return Me.velocidadEfectivaField
            End Get
            Set
                Me.velocidadEfectivaField = value
                Me.RaisePropertyChanged("VelocidadEfectiva")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property VelocidadObjetivo() As Double
            Get
                Return Me.velocidadObjetivoField
            End Get
            Set
                Me.velocidadObjetivoField = value
                Me.RaisePropertyChanged("VelocidadObjetivo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property TipoRecurso() As String
            Get
                Return Me.tipoRecursoField
            End Get
            Set
                Me.tipoRecursoField = value
                Me.RaisePropertyChanged("TipoRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property DescripcionFecha() As String
            Get
                Return Me.descripcionFechaField
            End Get
            Set
                Me.descripcionFechaField = value
                Me.RaisePropertyChanged("DescripcionFecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property BuscarFechaInicio() As Date
            Get
                Return Me.buscarFechaInicioField
            End Get
            Set
                Me.buscarFechaInicioField = value
                Me.RaisePropertyChanged("BuscarFechaInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property BuscarFechaFin() As Date
            Get
                Return Me.buscarFechaFinField
            End Get
            Set
                Me.buscarFechaFinField = value
                Me.RaisePropertyChanged("BuscarFechaFin")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ImpresionIndicadoresScrapEL
        Inherits BaseEL
        
        Private idRecursoField As String
        
        Private añoField As String
        
        Private mesField As String
        
        Private sumaKilosScrapField As Double
        
        Private sumaKilosProduccionField As Double
        
        Private sumaKilosRegulacionField As Double
        
        Private mermaObjetivoField As Double
        
        Private mermaResultanteField As Double
        
        Private tipoRecursoField As String
        
        Private descripcionFechaField As String
        
        Private buscarFechaInicioField As Date
        
        Private buscarFechaFinField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdRecurso() As String
            Get
                Return Me.idRecursoField
            End Get
            Set
                Me.idRecursoField = value
                Me.RaisePropertyChanged("IdRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Año() As String
            Get
                Return Me.añoField
            End Get
            Set
                Me.añoField = value
                Me.RaisePropertyChanged("Año")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Mes() As String
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
                Me.RaisePropertyChanged("Mes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property SumaKilosScrap() As Double
            Get
                Return Me.sumaKilosScrapField
            End Get
            Set
                Me.sumaKilosScrapField = value
                Me.RaisePropertyChanged("SumaKilosScrap")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property SumaKilosProduccion() As Double
            Get
                Return Me.sumaKilosProduccionField
            End Get
            Set
                Me.sumaKilosProduccionField = value
                Me.RaisePropertyChanged("SumaKilosProduccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property SumaKilosRegulacion() As Double
            Get
                Return Me.sumaKilosRegulacionField
            End Get
            Set
                Me.sumaKilosRegulacionField = value
                Me.RaisePropertyChanged("SumaKilosRegulacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property MermaObjetivo() As Double
            Get
                Return Me.mermaObjetivoField
            End Get
            Set
                Me.mermaObjetivoField = value
                Me.RaisePropertyChanged("MermaObjetivo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property MermaResultante() As Double
            Get
                Return Me.mermaResultanteField
            End Get
            Set
                Me.mermaResultanteField = value
                Me.RaisePropertyChanged("MermaResultante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property TipoRecurso() As String
            Get
                Return Me.tipoRecursoField
            End Get
            Set
                Me.tipoRecursoField = value
                Me.RaisePropertyChanged("TipoRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property DescripcionFecha() As String
            Get
                Return Me.descripcionFechaField
            End Get
            Set
                Me.descripcionFechaField = value
                Me.RaisePropertyChanged("DescripcionFecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property BuscarFechaInicio() As Date
            Get
                Return Me.buscarFechaInicioField
            End Get
            Set
                Me.buscarFechaInicioField = value
                Me.RaisePropertyChanged("BuscarFechaInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property BuscarFechaFin() As Date
            Get
                Return Me.buscarFechaFinField
            End Get
            Set
                Me.buscarFechaFinField = value
                Me.RaisePropertyChanged("BuscarFechaFin")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ImpresionIndicadoresMetrosEL
        Inherits BaseEL
        
        Private idRecursoField As String
        
        Private añoField As String
        
        Private mesField As String
        
        Private produccionMetrosMilesField As Double
        
        Private metrosObjetivosField As Double
        
        Private metrosCumplidosField As Double
        
        Private tipoRecursoField As String
        
        Private descripcionFechaField As String
        
        Private buscarFechaInicioField As Date
        
        Private buscarFechaFinField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdRecurso() As String
            Get
                Return Me.idRecursoField
            End Get
            Set
                Me.idRecursoField = value
                Me.RaisePropertyChanged("IdRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Año() As String
            Get
                Return Me.añoField
            End Get
            Set
                Me.añoField = value
                Me.RaisePropertyChanged("Año")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Mes() As String
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
                Me.RaisePropertyChanged("Mes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ProduccionMetrosMiles() As Double
            Get
                Return Me.produccionMetrosMilesField
            End Get
            Set
                Me.produccionMetrosMilesField = value
                Me.RaisePropertyChanged("ProduccionMetrosMiles")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property MetrosObjetivos() As Double
            Get
                Return Me.metrosObjetivosField
            End Get
            Set
                Me.metrosObjetivosField = value
                Me.RaisePropertyChanged("MetrosObjetivos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property MetrosCumplidos() As Double
            Get
                Return Me.metrosCumplidosField
            End Get
            Set
                Me.metrosCumplidosField = value
                Me.RaisePropertyChanged("MetrosCumplidos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property TipoRecurso() As String
            Get
                Return Me.tipoRecursoField
            End Get
            Set
                Me.tipoRecursoField = value
                Me.RaisePropertyChanged("TipoRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property DescripcionFecha() As String
            Get
                Return Me.descripcionFechaField
            End Get
            Set
                Me.descripcionFechaField = value
                Me.RaisePropertyChanged("DescripcionFecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property BuscarFechaInicio() As Date
            Get
                Return Me.buscarFechaInicioField
            End Get
            Set
                Me.buscarFechaInicioField = value
                Me.RaisePropertyChanged("BuscarFechaInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property BuscarFechaFin() As Date
            Get
                Return Me.buscarFechaFinField
            End Get
            Set
                Me.buscarFechaFinField = value
                Me.RaisePropertyChanged("BuscarFechaFin")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ImpresionIndicadoresSetUpEL
        Inherits BaseEL
        
        Private idRecursoField As String
        
        Private añoField As String
        
        Private mesField As String
        
        Private numeroCambiosField As Double
        
        Private setUpPromedioField As Double
        
        Private setUpObjetivoField As Double
        
        Private horasAcumuladasField As Double
        
        Private setUpPromedioHeptacromiaField As Double
        
        Private setUpObjetivoHeptacromiaField As Double
        
        Private setUpPromedioSinHeptacromiaField As Double
        
        Private setUpObjetivoSinHeptacromiaField As Double
        
        Private tipoRecursoField As String
        
        Private descripcionFechaField As String
        
        Private buscarFechaInicioField As Date
        
        Private buscarFechaFinField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdRecurso() As String
            Get
                Return Me.idRecursoField
            End Get
            Set
                Me.idRecursoField = value
                Me.RaisePropertyChanged("IdRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Año() As String
            Get
                Return Me.añoField
            End Get
            Set
                Me.añoField = value
                Me.RaisePropertyChanged("Año")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Mes() As String
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
                Me.RaisePropertyChanged("Mes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property NumeroCambios() As Double
            Get
                Return Me.numeroCambiosField
            End Get
            Set
                Me.numeroCambiosField = value
                Me.RaisePropertyChanged("NumeroCambios")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property SetUpPromedio() As Double
            Get
                Return Me.setUpPromedioField
            End Get
            Set
                Me.setUpPromedioField = value
                Me.RaisePropertyChanged("SetUpPromedio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property SetUpObjetivo() As Double
            Get
                Return Me.setUpObjetivoField
            End Get
            Set
                Me.setUpObjetivoField = value
                Me.RaisePropertyChanged("SetUpObjetivo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property HorasAcumuladas() As Double
            Get
                Return Me.horasAcumuladasField
            End Get
            Set
                Me.horasAcumuladasField = value
                Me.RaisePropertyChanged("HorasAcumuladas")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property SetUpPromedioHeptacromia() As Double
            Get
                Return Me.setUpPromedioHeptacromiaField
            End Get
            Set
                Me.setUpPromedioHeptacromiaField = value
                Me.RaisePropertyChanged("SetUpPromedioHeptacromia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property SetUpObjetivoHeptacromia() As Double
            Get
                Return Me.setUpObjetivoHeptacromiaField
            End Get
            Set
                Me.setUpObjetivoHeptacromiaField = value
                Me.RaisePropertyChanged("SetUpObjetivoHeptacromia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property SetUpPromedioSinHeptacromia() As Double
            Get
                Return Me.setUpPromedioSinHeptacromiaField
            End Get
            Set
                Me.setUpPromedioSinHeptacromiaField = value
                Me.RaisePropertyChanged("SetUpPromedioSinHeptacromia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property SetUpObjetivoSinHeptacromia() As Double
            Get
                Return Me.setUpObjetivoSinHeptacromiaField
            End Get
            Set
                Me.setUpObjetivoSinHeptacromiaField = value
                Me.RaisePropertyChanged("SetUpObjetivoSinHeptacromia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property TipoRecurso() As String
            Get
                Return Me.tipoRecursoField
            End Get
            Set
                Me.tipoRecursoField = value
                Me.RaisePropertyChanged("TipoRecurso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property DescripcionFecha() As String
            Get
                Return Me.descripcionFechaField
            End Get
            Set
                Me.descripcionFechaField = value
                Me.RaisePropertyChanged("DescripcionFecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property BuscarFechaInicio() As Date
            Get
                Return Me.buscarFechaInicioField
            End Get
            Set
                Me.buscarFechaInicioField = value
                Me.RaisePropertyChanged("BuscarFechaInicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property BuscarFechaFin() As Date
            Get
                Return Me.buscarFechaFinField
            End Get
            Set
                Me.buscarFechaFinField = value
                Me.RaisePropertyChanged("BuscarFechaFin")
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresSetUpRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public FechaCreacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public FechaEliminacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public FechaModificacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public FlagEstado As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public UsuarioCreacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public UsuarioEliminacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public UsuarioModificacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public IdRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public Año As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public Mes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public NumeroCambios As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public SetUpPromedio As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public SetUpObjetivo As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public HorasAcumuladas As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=14)>  _
        Public SetUpPromedioHeptacromia As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=15)>  _
        Public SetUpObjetivoHeptacromia As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=16)>  _
        Public SetUpPromedioSinHeptacromia As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=17)>  _
        Public SetUpObjetivoSinHeptacromia As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=18)>  _
        Public TipoRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=19)>  _
        Public DescripcionFecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=20)>  _
        Public BuscarFechaInicio As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=21)>  _
        Public BuscarFechaFin As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal FechaCreacion As Date,  _
                    ByVal FechaEliminacion As Date,  _
                    ByVal FechaModificacion As Date,  _
                    ByVal FlagEstado As Integer,  _
                    ByVal UsuarioCreacion As String,  _
                    ByVal UsuarioEliminacion As String,  _
                    ByVal UsuarioModificacion As String,  _
                    ByVal IdRecurso As String,  _
                    ByVal Año As String,  _
                    ByVal Mes As String,  _
                    ByVal NumeroCambios As Double,  _
                    ByVal SetUpPromedio As Double,  _
                    ByVal SetUpObjetivo As Double,  _
                    ByVal HorasAcumuladas As Double,  _
                    ByVal SetUpPromedioHeptacromia As Double,  _
                    ByVal SetUpObjetivoHeptacromia As Double,  _
                    ByVal SetUpPromedioSinHeptacromia As Double,  _
                    ByVal SetUpObjetivoSinHeptacromia As Double,  _
                    ByVal TipoRecurso As String,  _
                    ByVal DescripcionFecha As String,  _
                    ByVal BuscarFechaInicio As Date,  _
                    ByVal BuscarFechaFin As Date)
            MyBase.New
            Me.FechaCreacion = FechaCreacion
            Me.FechaEliminacion = FechaEliminacion
            Me.FechaModificacion = FechaModificacion
            Me.FlagEstado = FlagEstado
            Me.UsuarioCreacion = UsuarioCreacion
            Me.UsuarioEliminacion = UsuarioEliminacion
            Me.UsuarioModificacion = UsuarioModificacion
            Me.IdRecurso = IdRecurso
            Me.Año = Año
            Me.Mes = Mes
            Me.NumeroCambios = NumeroCambios
            Me.SetUpPromedio = SetUpPromedio
            Me.SetUpObjetivo = SetUpObjetivo
            Me.HorasAcumuladas = HorasAcumuladas
            Me.SetUpPromedioHeptacromia = SetUpPromedioHeptacromia
            Me.SetUpObjetivoHeptacromia = SetUpObjetivoHeptacromia
            Me.SetUpPromedioSinHeptacromia = SetUpPromedioSinHeptacromia
            Me.SetUpObjetivoSinHeptacromia = SetUpObjetivoSinHeptacromia
            Me.TipoRecurso = TipoRecurso
            Me.DescripcionFecha = DescripcionFecha
            Me.BuscarFechaInicio = BuscarFechaInicio
            Me.BuscarFechaFin = BuscarFechaFin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresSetUpResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As ImpresionIndicadoresService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListaIndicadoresSetUp() As ImpresionIndicadoresService.ImpresionIndicadoresSetUpEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public ListaIndicadoresSetUpConHeptacromia() As ImpresionIndicadoresService.ImpresionIndicadoresSetUpEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public ListaIndicadoresSetUpSinHeptacromia() As ImpresionIndicadoresService.ImpresionIndicadoresSetUpEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As ImpresionIndicadoresService.BaseErrorEL, ByVal ListaIndicadoresSetUp() As ImpresionIndicadoresService.ImpresionIndicadoresSetUpEL, ByVal ListaIndicadoresSetUpConHeptacromia() As ImpresionIndicadoresService.ImpresionIndicadoresSetUpEL, ByVal ListaIndicadoresSetUpSinHeptacromia() As ImpresionIndicadoresService.ImpresionIndicadoresSetUpEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListaIndicadoresSetUp = ListaIndicadoresSetUp
            Me.ListaIndicadoresSetUpConHeptacromia = ListaIndicadoresSetUpConHeptacromia
            Me.ListaIndicadoresSetUpSinHeptacromia = ListaIndicadoresSetUpSinHeptacromia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresMetrosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public FechaCreacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public FechaEliminacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public FechaModificacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public FlagEstado As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public UsuarioCreacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public UsuarioEliminacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public UsuarioModificacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public IdRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public Año As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public Mes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public ProduccionMetrosMiles As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public MetrosObjetivos As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public MetrosCumplidos As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public TipoRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=14)>  _
        Public DescripcionFecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=15)>  _
        Public BuscarFechaInicio As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=16)>  _
        Public BuscarFechaFin As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal FechaCreacion As Date,  _
                    ByVal FechaEliminacion As Date,  _
                    ByVal FechaModificacion As Date,  _
                    ByVal FlagEstado As Integer,  _
                    ByVal UsuarioCreacion As String,  _
                    ByVal UsuarioEliminacion As String,  _
                    ByVal UsuarioModificacion As String,  _
                    ByVal IdRecurso As String,  _
                    ByVal Año As String,  _
                    ByVal Mes As String,  _
                    ByVal ProduccionMetrosMiles As Double,  _
                    ByVal MetrosObjetivos As Double,  _
                    ByVal MetrosCumplidos As Double,  _
                    ByVal TipoRecurso As String,  _
                    ByVal DescripcionFecha As String,  _
                    ByVal BuscarFechaInicio As Date,  _
                    ByVal BuscarFechaFin As Date)
            MyBase.New
            Me.FechaCreacion = FechaCreacion
            Me.FechaEliminacion = FechaEliminacion
            Me.FechaModificacion = FechaModificacion
            Me.FlagEstado = FlagEstado
            Me.UsuarioCreacion = UsuarioCreacion
            Me.UsuarioEliminacion = UsuarioEliminacion
            Me.UsuarioModificacion = UsuarioModificacion
            Me.IdRecurso = IdRecurso
            Me.Año = Año
            Me.Mes = Mes
            Me.ProduccionMetrosMiles = ProduccionMetrosMiles
            Me.MetrosObjetivos = MetrosObjetivos
            Me.MetrosCumplidos = MetrosCumplidos
            Me.TipoRecurso = TipoRecurso
            Me.DescripcionFecha = DescripcionFecha
            Me.BuscarFechaInicio = BuscarFechaInicio
            Me.BuscarFechaFin = BuscarFechaFin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresMetrosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As ImpresionIndicadoresService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListaProduccionMetros() As ImpresionIndicadoresService.ImpresionIndicadoresMetrosEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As ImpresionIndicadoresService.BaseErrorEL, ByVal ListaProduccionMetros() As ImpresionIndicadoresService.ImpresionIndicadoresMetrosEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListaProduccionMetros = ListaProduccionMetros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresScrapRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public FechaCreacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public FechaEliminacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public FechaModificacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public FlagEstado As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public UsuarioCreacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public UsuarioEliminacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public UsuarioModificacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public IdRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public Año As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public Mes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public SumaKilosScrap As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public SumaKilosProduccion As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public SumaKilosRegulacion As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public MermaObjetivo As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=14)>  _
        Public MermaResultante As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=15)>  _
        Public TipoRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=16)>  _
        Public DescripcionFecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=17)>  _
        Public BuscarFechaInicio As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=18)>  _
        Public BuscarFechaFin As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal FechaCreacion As Date,  _
                    ByVal FechaEliminacion As Date,  _
                    ByVal FechaModificacion As Date,  _
                    ByVal FlagEstado As Integer,  _
                    ByVal UsuarioCreacion As String,  _
                    ByVal UsuarioEliminacion As String,  _
                    ByVal UsuarioModificacion As String,  _
                    ByVal IdRecurso As String,  _
                    ByVal Año As String,  _
                    ByVal Mes As String,  _
                    ByVal SumaKilosScrap As Double,  _
                    ByVal SumaKilosProduccion As Double,  _
                    ByVal SumaKilosRegulacion As Double,  _
                    ByVal MermaObjetivo As Double,  _
                    ByVal MermaResultante As Double,  _
                    ByVal TipoRecurso As String,  _
                    ByVal DescripcionFecha As String,  _
                    ByVal BuscarFechaInicio As Date,  _
                    ByVal BuscarFechaFin As Date)
            MyBase.New
            Me.FechaCreacion = FechaCreacion
            Me.FechaEliminacion = FechaEliminacion
            Me.FechaModificacion = FechaModificacion
            Me.FlagEstado = FlagEstado
            Me.UsuarioCreacion = UsuarioCreacion
            Me.UsuarioEliminacion = UsuarioEliminacion
            Me.UsuarioModificacion = UsuarioModificacion
            Me.IdRecurso = IdRecurso
            Me.Año = Año
            Me.Mes = Mes
            Me.SumaKilosScrap = SumaKilosScrap
            Me.SumaKilosProduccion = SumaKilosProduccion
            Me.SumaKilosRegulacion = SumaKilosRegulacion
            Me.MermaObjetivo = MermaObjetivo
            Me.MermaResultante = MermaResultante
            Me.TipoRecurso = TipoRecurso
            Me.DescripcionFecha = DescripcionFecha
            Me.BuscarFechaInicio = BuscarFechaInicio
            Me.BuscarFechaFin = BuscarFechaFin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresScrapResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As ImpresionIndicadoresService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListaProduccionScrap() As ImpresionIndicadoresService.ImpresionIndicadoresScrapEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As ImpresionIndicadoresService.BaseErrorEL, ByVal ListaProduccionScrap() As ImpresionIndicadoresService.ImpresionIndicadoresScrapEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListaProduccionScrap = ListaProduccionScrap
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresVelocidadRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public FechaCreacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public FechaEliminacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public FechaModificacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public FlagEstado As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public UsuarioCreacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public UsuarioEliminacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public UsuarioModificacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public IdRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public Año As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public Mes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public SumaMetros As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public SumaHoras As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public VelocidadTotal As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public VelocidadEfectiva As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=14)>  _
        Public VelocidadObjetivo As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=15)>  _
        Public TipoRecurso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=16)>  _
        Public DescripcionFecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=17)>  _
        Public BuscarFechaInicio As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=18)>  _
        Public BuscarFechaFin As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal FechaCreacion As Date,  _
                    ByVal FechaEliminacion As Date,  _
                    ByVal FechaModificacion As Date,  _
                    ByVal FlagEstado As Integer,  _
                    ByVal UsuarioCreacion As String,  _
                    ByVal UsuarioEliminacion As String,  _
                    ByVal UsuarioModificacion As String,  _
                    ByVal IdRecurso As String,  _
                    ByVal Año As String,  _
                    ByVal Mes As String,  _
                    ByVal SumaMetros As Double,  _
                    ByVal SumaHoras As Double,  _
                    ByVal VelocidadTotal As Double,  _
                    ByVal VelocidadEfectiva As Double,  _
                    ByVal VelocidadObjetivo As Double,  _
                    ByVal TipoRecurso As String,  _
                    ByVal DescripcionFecha As String,  _
                    ByVal BuscarFechaInicio As Date,  _
                    ByVal BuscarFechaFin As Date)
            MyBase.New
            Me.FechaCreacion = FechaCreacion
            Me.FechaEliminacion = FechaEliminacion
            Me.FechaModificacion = FechaModificacion
            Me.FlagEstado = FlagEstado
            Me.UsuarioCreacion = UsuarioCreacion
            Me.UsuarioEliminacion = UsuarioEliminacion
            Me.UsuarioModificacion = UsuarioModificacion
            Me.IdRecurso = IdRecurso
            Me.Año = Año
            Me.Mes = Mes
            Me.SumaMetros = SumaMetros
            Me.SumaHoras = SumaHoras
            Me.VelocidadTotal = VelocidadTotal
            Me.VelocidadEfectiva = VelocidadEfectiva
            Me.VelocidadObjetivo = VelocidadObjetivo
            Me.TipoRecurso = TipoRecurso
            Me.DescripcionFecha = DescripcionFecha
            Me.BuscarFechaInicio = BuscarFechaInicio
            Me.BuscarFechaFin = BuscarFechaFin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ImpresionIndicadoresVelocidadResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As ImpresionIndicadoresService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListaIndicadoresVelocidad() As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As ImpresionIndicadoresService.BaseErrorEL, ByVal ListaIndicadoresVelocidad() As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListaIndicadoresVelocidad = ListaIndicadoresVelocidad
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IImpresionIndicadoresChannel
        Inherits ImpresionIndicadoresService.IImpresionIndicadores, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ImpresionIndicadoresClient
        Inherits System.ServiceModel.ClientBase(Of ImpresionIndicadoresService.IImpresionIndicadores)
        Implements ImpresionIndicadoresService.IImpresionIndicadores
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListaIndicadoresSetUpIndividual(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresSetUpIndividual
            Return MyBase.Channel.ListaIndicadoresSetUpIndividual(request)
        End Function
        
        Public Function ListaIndicadoresSetUpTotal(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresSetUpTotal
            Return MyBase.Channel.ListaIndicadoresSetUpTotal(request)
        End Function
        
        Public Function ListaIndicadoresSetUpConHeptacromia(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresSetUpConHeptacromia
            Return MyBase.Channel.ListaIndicadoresSetUpConHeptacromia(request)
        End Function
        
        Public Function ListaIndicadoresSetUpSinHeptacromiaIndividual(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresSetUpSinHeptacromiaIndividual
            Return MyBase.Channel.ListaIndicadoresSetUpSinHeptacromiaIndividual(request)
        End Function
        
        Public Function ListaIndicadoresSetUpSinHeptacromiaTotal(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresSetUpRequest) As ImpresionIndicadoresService.ImpresionIndicadoresSetUpResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresSetUpSinHeptacromiaTotal
            Return MyBase.Channel.ListaIndicadoresSetUpSinHeptacromiaTotal(request)
        End Function
        
        Public Function ListaIndicadoresMetrosIndividuales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresMetrosRequest) As ImpresionIndicadoresService.ImpresionIndicadoresMetrosResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresMetrosIndividuales
            Return MyBase.Channel.ListaIndicadoresMetrosIndividuales(request)
        End Function
        
        Public Function ListaIndicadoresMetrosTotales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresMetrosRequest) As ImpresionIndicadoresService.ImpresionIndicadoresMetrosResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresMetrosTotales
            Return MyBase.Channel.ListaIndicadoresMetrosTotales(request)
        End Function
        
        Public Function ListaIndicadoresScrapIndividuales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresScrapRequest) As ImpresionIndicadoresService.ImpresionIndicadoresScrapResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresScrapIndividuales
            Return MyBase.Channel.ListaIndicadoresScrapIndividuales(request)
        End Function
        
        Public Function ListaIndicadoresScrapTotales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresScrapRequest) As ImpresionIndicadoresService.ImpresionIndicadoresScrapResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresScrapTotales
            Return MyBase.Channel.ListaIndicadoresScrapTotales(request)
        End Function
        
        Public Function ListaIndicadoresVelocidadIndividuales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadRequest) As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresVelocidadIndividuales
            Return MyBase.Channel.ListaIndicadoresVelocidadIndividuales(request)
        End Function
        
        Public Function ListaIndicadoresVelocidadTotales(ByVal request As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadRequest) As ImpresionIndicadoresService.ImpresionIndicadoresVelocidadResponse Implements ImpresionIndicadoresService.IImpresionIndicadores.ListaIndicadoresVelocidadTotales
            Return MyBase.Channel.ListaIndicadoresVelocidadTotales(request)
        End Function
    End Class
End Namespace
