'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DisenoIndicadoresService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:resinplast:Indicadores:DisenoIndicadores", ConfigurationName:="DisenoIndicadoresService.IDiseñoIndicadores")>  _
    Public Interface IDiseñoIndicadores
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarAperturasDia", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarAperturasDia(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarAperturasCompletadasSemana", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarAperturasCompletadasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarAperturasSemana", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarAperturasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarAperturasDiaDetalle", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarAperturasDiaDetalle(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarAperturasCompletadasPorUsuario"& _ 
            "", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarAperturasCompletadasPorUsuario(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarPrepensaDia", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarPrepensaDia(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarPreprensaDiaDetalle", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarPreprensaDiaDetalle(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarPreprensasSemana", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarPreprensasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarPreprensasCompletadasSemana", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarPreprensasCompletadasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:Indicadores:DisenoIndicadores:ListarPrepensaDiaPruebaColor", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarPrepensaDiaPruebaColor(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BaseErrorEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private descripcionField As String
        
        Private parametrosField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("Codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Parametros() As String
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
                Me.RaisePropertyChanged("Parametros")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DiseñoIndicadoresPreprensasEL)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DiseñoIndicadoresAperturaEL)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BaseEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private flagEstadoField As Integer
        
        Private usuarioCreacionField As String
        
        Private fechaCreacionField As Date
        
        Private usuarioModificacionField As String
        
        Private fechaModificacionField As Date
        
        Private usuarioEliminacionField As String
        
        Private fechaEliminacionField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property FlagEstado() As Integer
            Get
                Return Me.flagEstadoField
            End Get
            Set
                Me.flagEstadoField = value
                Me.RaisePropertyChanged("FlagEstado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property UsuarioCreacion() As String
            Get
                Return Me.usuarioCreacionField
            End Get
            Set
                Me.usuarioCreacionField = value
                Me.RaisePropertyChanged("UsuarioCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property FechaCreacion() As Date
            Get
                Return Me.fechaCreacionField
            End Get
            Set
                Me.fechaCreacionField = value
                Me.RaisePropertyChanged("FechaCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property UsuarioModificacion() As String
            Get
                Return Me.usuarioModificacionField
            End Get
            Set
                Me.usuarioModificacionField = value
                Me.RaisePropertyChanged("UsuarioModificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property FechaModificacion() As Date
            Get
                Return Me.fechaModificacionField
            End Get
            Set
                Me.fechaModificacionField = value
                Me.RaisePropertyChanged("FechaModificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property UsuarioEliminacion() As String
            Get
                Return Me.usuarioEliminacionField
            End Get
            Set
                Me.usuarioEliminacionField = value
                Me.RaisePropertyChanged("UsuarioEliminacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property FechaEliminacion() As Date
            Get
                Return Me.fechaEliminacionField
            End Get
            Set
                Me.fechaEliminacionField = value
                Me.RaisePropertyChanged("FechaEliminacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DiseñoIndicadoresPreprensasEL
        Inherits BaseEL
        
        Private idPizarraInternoField As String
        
        Private nroLegalOrdenTrabajoField As String
        
        Private nombreClienteField As String
        
        Private nombreProductoField As String
        
        Private fechaEnviadoClicheField As Date
        
        Private totalTrabajosField As String
        
        Private totalTrabajosAñoField As String
        
        Private totalTrabajosmesField As String
        
        Private totalTrabajosdiaField As String
        
        Private fechaEnviadoClichemesField As String
        
        Private añoField As String
        
        Private mesField As String
        
        Private numeroSemanaField As String
        
        Private fechaIniSemEnviadoProcesoField As Date
        
        Private fechaFinSemEnviadoProcesoField As Date
        
        Private promedioSemField As String
        
        Private trabajosSinCompletarField As String
        
        Private fechaEnviadoProcesoField As Date
        
        Private descripcionFechaField As String
        
        Private estadoTrabajoField As String
        
        Private fechaIniSemEnviadoClicheField As Date
        
        Private fechaFinSemEnviadoClicheField As Date
        
        Private tiempoPreprensaField As Integer
        
        Private trabajosPromedioField As String
        
        Private idEventoControlField As String
        
        Private trabajosConPCField As String
        
        Private trabajosSinPCField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdPizarraInterno() As String
            Get
                Return Me.idPizarraInternoField
            End Get
            Set
                Me.idPizarraInternoField = value
                Me.RaisePropertyChanged("IdPizarraInterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NroLegalOrdenTrabajo() As String
            Get
                Return Me.nroLegalOrdenTrabajoField
            End Get
            Set
                Me.nroLegalOrdenTrabajoField = value
                Me.RaisePropertyChanged("NroLegalOrdenTrabajo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NombreCliente() As String
            Get
                Return Me.nombreClienteField
            End Get
            Set
                Me.nombreClienteField = value
                Me.RaisePropertyChanged("NombreCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property NombreProducto() As String
            Get
                Return Me.nombreProductoField
            End Get
            Set
                Me.nombreProductoField = value
                Me.RaisePropertyChanged("NombreProducto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property FechaEnviadoCliche() As Date
            Get
                Return Me.fechaEnviadoClicheField
            End Get
            Set
                Me.fechaEnviadoClicheField = value
                Me.RaisePropertyChanged("FechaEnviadoCliche")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property TotalTrabajos() As String
            Get
                Return Me.totalTrabajosField
            End Get
            Set
                Me.totalTrabajosField = value
                Me.RaisePropertyChanged("TotalTrabajos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property TotalTrabajosAño() As String
            Get
                Return Me.totalTrabajosAñoField
            End Get
            Set
                Me.totalTrabajosAñoField = value
                Me.RaisePropertyChanged("TotalTrabajosAño")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property TotalTrabajosmes() As String
            Get
                Return Me.totalTrabajosmesField
            End Get
            Set
                Me.totalTrabajosmesField = value
                Me.RaisePropertyChanged("TotalTrabajosmes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property TotalTrabajosdia() As String
            Get
                Return Me.totalTrabajosdiaField
            End Get
            Set
                Me.totalTrabajosdiaField = value
                Me.RaisePropertyChanged("TotalTrabajosdia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property FechaEnviadoClichemes() As String
            Get
                Return Me.fechaEnviadoClichemesField
            End Get
            Set
                Me.fechaEnviadoClichemesField = value
                Me.RaisePropertyChanged("FechaEnviadoClichemes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Año() As String
            Get
                Return Me.añoField
            End Get
            Set
                Me.añoField = value
                Me.RaisePropertyChanged("Año")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property mes() As String
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
                Me.RaisePropertyChanged("mes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property NumeroSemana() As String
            Get
                Return Me.numeroSemanaField
            End Get
            Set
                Me.numeroSemanaField = value
                Me.RaisePropertyChanged("NumeroSemana")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property FechaIniSemEnviadoProceso() As Date
            Get
                Return Me.fechaIniSemEnviadoProcesoField
            End Get
            Set
                Me.fechaIniSemEnviadoProcesoField = value
                Me.RaisePropertyChanged("FechaIniSemEnviadoProceso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property FechaFinSemEnviadoProceso() As Date
            Get
                Return Me.fechaFinSemEnviadoProcesoField
            End Get
            Set
                Me.fechaFinSemEnviadoProcesoField = value
                Me.RaisePropertyChanged("FechaFinSemEnviadoProceso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property PromedioSem() As String
            Get
                Return Me.promedioSemField
            End Get
            Set
                Me.promedioSemField = value
                Me.RaisePropertyChanged("PromedioSem")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property TrabajosSinCompletar() As String
            Get
                Return Me.trabajosSinCompletarField
            End Get
            Set
                Me.trabajosSinCompletarField = value
                Me.RaisePropertyChanged("TrabajosSinCompletar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property FechaEnviadoProceso() As Date
            Get
                Return Me.fechaEnviadoProcesoField
            End Get
            Set
                Me.fechaEnviadoProcesoField = value
                Me.RaisePropertyChanged("FechaEnviadoProceso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property DescripcionFecha() As String
            Get
                Return Me.descripcionFechaField
            End Get
            Set
                Me.descripcionFechaField = value
                Me.RaisePropertyChanged("DescripcionFecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property EstadoTrabajo() As String
            Get
                Return Me.estadoTrabajoField
            End Get
            Set
                Me.estadoTrabajoField = value
                Me.RaisePropertyChanged("EstadoTrabajo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=20)>  _
        Public Property FechaIniSemEnviadoCliche() As Date
            Get
                Return Me.fechaIniSemEnviadoClicheField
            End Get
            Set
                Me.fechaIniSemEnviadoClicheField = value
                Me.RaisePropertyChanged("FechaIniSemEnviadoCliche")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=21)>  _
        Public Property FechaFinSemEnviadoCliche() As Date
            Get
                Return Me.fechaFinSemEnviadoClicheField
            End Get
            Set
                Me.fechaFinSemEnviadoClicheField = value
                Me.RaisePropertyChanged("FechaFinSemEnviadoCliche")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=22)>  _
        Public Property TiempoPreprensa() As Integer
            Get
                Return Me.tiempoPreprensaField
            End Get
            Set
                Me.tiempoPreprensaField = value
                Me.RaisePropertyChanged("TiempoPreprensa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=23)>  _
        Public Property TrabajosPromedio() As String
            Get
                Return Me.trabajosPromedioField
            End Get
            Set
                Me.trabajosPromedioField = value
                Me.RaisePropertyChanged("TrabajosPromedio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=24)>  _
        Public Property IdEventoControl() As String
            Get
                Return Me.idEventoControlField
            End Get
            Set
                Me.idEventoControlField = value
                Me.RaisePropertyChanged("IdEventoControl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=25)>  _
        Public Property TrabajosConPC() As String
            Get
                Return Me.trabajosConPCField
            End Get
            Set
                Me.trabajosConPCField = value
                Me.RaisePropertyChanged("TrabajosConPC")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=26)>  _
        Public Property TrabajosSinPC() As String
            Get
                Return Me.trabajosSinPCField
            End Get
            Set
                Me.trabajosSinPCField = value
                Me.RaisePropertyChanged("TrabajosSinPC")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DiseñoIndicadoresAperturaEL
        Inherits BaseEL
        
        Private idOrdenTrabajoField As String
        
        Private nroLegalOrdenTrabajoField As String
        
        Private nombreClienteField As String
        
        Private nombreProductoField As String
        
        Private fechaEnAprobacionClienteField As Date
        
        Private totalTrabajosField As String
        
        Private totalTrabajosAñoField As String
        
        Private totalTrabajosmesField As String
        
        Private totalTrabajosdiaField As String
        
        Private fechaEnAprobacionClientemesField As String
        
        Private añoField As String
        
        Private mesField As String
        
        Private numeroSemanaField As String
        
        Private fechaIniSemEnAprobacionClienteField As Date
        
        Private fechaFinSemEnAprobacionClienteField As Date
        
        Private promedioSemField As String
        
        Private trabajosSinCompletarField As String
        
        Private fechaEnviadoDisenoField As Date
        
        Private descripcionFechaField As String
        
        Private estadoTrabajoField As String
        
        Private fechaIniSemEnviadoDisenoField As Date
        
        Private fechaFinSemEnviadoDisenoField As Date
        
        Private tiempoAperturaHorasField As Double
        
        Private trabajosPromedioField As String
        
        Private usuarioEnAprobacionClienteField As String
        
        Private usuarioEnviadoDisenoField As String
        
        Private tiempoDeAperturaField As Double
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdOrdenTrabajo() As String
            Get
                Return Me.idOrdenTrabajoField
            End Get
            Set
                Me.idOrdenTrabajoField = value
                Me.RaisePropertyChanged("IdOrdenTrabajo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NroLegalOrdenTrabajo() As String
            Get
                Return Me.nroLegalOrdenTrabajoField
            End Get
            Set
                Me.nroLegalOrdenTrabajoField = value
                Me.RaisePropertyChanged("NroLegalOrdenTrabajo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NombreCliente() As String
            Get
                Return Me.nombreClienteField
            End Get
            Set
                Me.nombreClienteField = value
                Me.RaisePropertyChanged("NombreCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property NombreProducto() As String
            Get
                Return Me.nombreProductoField
            End Get
            Set
                Me.nombreProductoField = value
                Me.RaisePropertyChanged("NombreProducto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property FechaEnAprobacionCliente() As Date
            Get
                Return Me.fechaEnAprobacionClienteField
            End Get
            Set
                Me.fechaEnAprobacionClienteField = value
                Me.RaisePropertyChanged("FechaEnAprobacionCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property TotalTrabajos() As String
            Get
                Return Me.totalTrabajosField
            End Get
            Set
                Me.totalTrabajosField = value
                Me.RaisePropertyChanged("TotalTrabajos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property TotalTrabajosAño() As String
            Get
                Return Me.totalTrabajosAñoField
            End Get
            Set
                Me.totalTrabajosAñoField = value
                Me.RaisePropertyChanged("TotalTrabajosAño")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property TotalTrabajosmes() As String
            Get
                Return Me.totalTrabajosmesField
            End Get
            Set
                Me.totalTrabajosmesField = value
                Me.RaisePropertyChanged("TotalTrabajosmes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property TotalTrabajosdia() As String
            Get
                Return Me.totalTrabajosdiaField
            End Get
            Set
                Me.totalTrabajosdiaField = value
                Me.RaisePropertyChanged("TotalTrabajosdia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property FechaEnAprobacionClientemes() As String
            Get
                Return Me.fechaEnAprobacionClientemesField
            End Get
            Set
                Me.fechaEnAprobacionClientemesField = value
                Me.RaisePropertyChanged("FechaEnAprobacionClientemes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Año() As String
            Get
                Return Me.añoField
            End Get
            Set
                Me.añoField = value
                Me.RaisePropertyChanged("Año")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property mes() As String
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
                Me.RaisePropertyChanged("mes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property NumeroSemana() As String
            Get
                Return Me.numeroSemanaField
            End Get
            Set
                Me.numeroSemanaField = value
                Me.RaisePropertyChanged("NumeroSemana")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property FechaIniSemEnAprobacionCliente() As Date
            Get
                Return Me.fechaIniSemEnAprobacionClienteField
            End Get
            Set
                Me.fechaIniSemEnAprobacionClienteField = value
                Me.RaisePropertyChanged("FechaIniSemEnAprobacionCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property FechaFinSemEnAprobacionCliente() As Date
            Get
                Return Me.fechaFinSemEnAprobacionClienteField
            End Get
            Set
                Me.fechaFinSemEnAprobacionClienteField = value
                Me.RaisePropertyChanged("FechaFinSemEnAprobacionCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property PromedioSem() As String
            Get
                Return Me.promedioSemField
            End Get
            Set
                Me.promedioSemField = value
                Me.RaisePropertyChanged("PromedioSem")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property TrabajosSinCompletar() As String
            Get
                Return Me.trabajosSinCompletarField
            End Get
            Set
                Me.trabajosSinCompletarField = value
                Me.RaisePropertyChanged("TrabajosSinCompletar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property FechaEnviadoDiseno() As Date
            Get
                Return Me.fechaEnviadoDisenoField
            End Get
            Set
                Me.fechaEnviadoDisenoField = value
                Me.RaisePropertyChanged("FechaEnviadoDiseno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property DescripcionFecha() As String
            Get
                Return Me.descripcionFechaField
            End Get
            Set
                Me.descripcionFechaField = value
                Me.RaisePropertyChanged("DescripcionFecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property EstadoTrabajo() As String
            Get
                Return Me.estadoTrabajoField
            End Get
            Set
                Me.estadoTrabajoField = value
                Me.RaisePropertyChanged("EstadoTrabajo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=20)>  _
        Public Property FechaIniSemEnviadoDiseno() As Date
            Get
                Return Me.fechaIniSemEnviadoDisenoField
            End Get
            Set
                Me.fechaIniSemEnviadoDisenoField = value
                Me.RaisePropertyChanged("FechaIniSemEnviadoDiseno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=21)>  _
        Public Property FechaFinSemEnviadoDiseno() As Date
            Get
                Return Me.fechaFinSemEnviadoDisenoField
            End Get
            Set
                Me.fechaFinSemEnviadoDisenoField = value
                Me.RaisePropertyChanged("FechaFinSemEnviadoDiseno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=22)>  _
        Public Property TiempoAperturaHoras() As Double
            Get
                Return Me.tiempoAperturaHorasField
            End Get
            Set
                Me.tiempoAperturaHorasField = value
                Me.RaisePropertyChanged("TiempoAperturaHoras")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=23)>  _
        Public Property TrabajosPromedio() As String
            Get
                Return Me.trabajosPromedioField
            End Get
            Set
                Me.trabajosPromedioField = value
                Me.RaisePropertyChanged("TrabajosPromedio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=24)>  _
        Public Property UsuarioEnAprobacionCliente() As String
            Get
                Return Me.usuarioEnAprobacionClienteField
            End Get
            Set
                Me.usuarioEnAprobacionClienteField = value
                Me.RaisePropertyChanged("UsuarioEnAprobacionCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=25)>  _
        Public Property UsuarioEnviadoDiseno() As String
            Get
                Return Me.usuarioEnviadoDisenoField
            End Get
            Set
                Me.usuarioEnviadoDisenoField = value
                Me.RaisePropertyChanged("UsuarioEnviadoDiseno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=26)>  _
        Public Property TiempoDeApertura() As Double
            Get
                Return Me.tiempoDeAperturaField
            End Get
            Set
                Me.tiempoDeAperturaField = value
                Me.RaisePropertyChanged("TiempoDeApertura")
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DiseñoIndicadoresAperturaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public IdOrdenTrabajo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public NroLegalOrdenTrabajo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public NombreCliente As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public NombreProducto As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public FechaEnAprobacionCliente As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public TotalTrabajos As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public TotalTrabajosAño As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public TotalTrabajosmes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public TotalTrabajosdia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public FechaEnAprobacionClientemes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public Año As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public mes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public NumeroSemana As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public FechaIniSemEnAprobacionCliente As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=14)>  _
        Public FechaFinSemEnAprobacionCliente As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=15)>  _
        Public PromedioSem As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=16)>  _
        Public TrabajosSinCompletar As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=17)>  _
        Public FechaEnviadoDiseno As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=18)>  _
        Public DescripcionFecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=19)>  _
        Public EstadoTrabajo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=20)>  _
        Public FechaIniSemEnviadoDiseno As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=21)>  _
        Public FechaFinSemEnviadoDiseno As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=22)>  _
        Public TiempoAperturaHoras As Double
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=23)>  _
        Public TiempoPromedio As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=24)>  _
        Public UsuarioEnAprobacionCliente As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=25)>  _
        Public UsuarioEnviadoDiseno As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=26)>  _
        Public TiempoDeApertura As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal IdOrdenTrabajo As String,  _
                    ByVal NroLegalOrdenTrabajo As String,  _
                    ByVal NombreCliente As String,  _
                    ByVal NombreProducto As String,  _
                    ByVal FechaEnAprobacionCliente As Date,  _
                    ByVal TotalTrabajos As String,  _
                    ByVal TotalTrabajosAño As String,  _
                    ByVal TotalTrabajosmes As String,  _
                    ByVal TotalTrabajosdia As String,  _
                    ByVal FechaEnAprobacionClientemes As String,  _
                    ByVal Año As String,  _
                    ByVal mes As String,  _
                    ByVal NumeroSemana As String,  _
                    ByVal FechaIniSemEnAprobacionCliente As Date,  _
                    ByVal FechaFinSemEnAprobacionCliente As Date,  _
                    ByVal PromedioSem As String,  _
                    ByVal TrabajosSinCompletar As String,  _
                    ByVal FechaEnviadoDiseno As Date,  _
                    ByVal DescripcionFecha As String,  _
                    ByVal EstadoTrabajo As String,  _
                    ByVal FechaIniSemEnviadoDiseno As Date,  _
                    ByVal FechaFinSemEnviadoDiseno As Date,  _
                    ByVal TiempoAperturaHoras As Double,  _
                    ByVal TiempoPromedio As String,  _
                    ByVal UsuarioEnAprobacionCliente As String,  _
                    ByVal UsuarioEnviadoDiseno As String,  _
                    ByVal TiempoDeApertura As Double)
            MyBase.New
            Me.IdOrdenTrabajo = IdOrdenTrabajo
            Me.NroLegalOrdenTrabajo = NroLegalOrdenTrabajo
            Me.NombreCliente = NombreCliente
            Me.NombreProducto = NombreProducto
            Me.FechaEnAprobacionCliente = FechaEnAprobacionCliente
            Me.TotalTrabajos = TotalTrabajos
            Me.TotalTrabajosAño = TotalTrabajosAño
            Me.TotalTrabajosmes = TotalTrabajosmes
            Me.TotalTrabajosdia = TotalTrabajosdia
            Me.FechaEnAprobacionClientemes = FechaEnAprobacionClientemes
            Me.Año = Año
            Me.mes = mes
            Me.NumeroSemana = NumeroSemana
            Me.FechaIniSemEnAprobacionCliente = FechaIniSemEnAprobacionCliente
            Me.FechaFinSemEnAprobacionCliente = FechaFinSemEnAprobacionCliente
            Me.PromedioSem = PromedioSem
            Me.TrabajosSinCompletar = TrabajosSinCompletar
            Me.FechaEnviadoDiseno = FechaEnviadoDiseno
            Me.DescripcionFecha = DescripcionFecha
            Me.EstadoTrabajo = EstadoTrabajo
            Me.FechaIniSemEnviadoDiseno = FechaIniSemEnviadoDiseno
            Me.FechaFinSemEnviadoDiseno = FechaFinSemEnviadoDiseno
            Me.TiempoAperturaHoras = TiempoAperturaHoras
            Me.TiempoPromedio = TiempoPromedio
            Me.UsuarioEnAprobacionCliente = UsuarioEnAprobacionCliente
            Me.UsuarioEnviadoDiseno = UsuarioEnviadoDiseno
            Me.TiempoDeApertura = TiempoDeApertura
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DiseñoIndicadoresAperturaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As DisenoIndicadoresService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListaIndicadorAperturasDia() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public ListaIndicadorAperturasDiaCliente() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public ListaIndicadorAperturasDiaDetalle() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public ListaIndicadorAperturasSemana() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public ListaIndicadorAperturasCompletadasSemana() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public ListarAperturasCompletadasPorUsuario() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As DisenoIndicadoresService.BaseErrorEL, ByVal ListaIndicadorAperturasDia() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL, ByVal ListaIndicadorAperturasDiaCliente() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL, ByVal ListaIndicadorAperturasDiaDetalle() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL, ByVal ListaIndicadorAperturasSemana() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL, ByVal ListaIndicadorAperturasCompletadasSemana() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL, ByVal ListarAperturasCompletadasPorUsuario() As DisenoIndicadoresService.DiseñoIndicadoresAperturaEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListaIndicadorAperturasDia = ListaIndicadorAperturasDia
            Me.ListaIndicadorAperturasDiaCliente = ListaIndicadorAperturasDiaCliente
            Me.ListaIndicadorAperturasDiaDetalle = ListaIndicadorAperturasDiaDetalle
            Me.ListaIndicadorAperturasSemana = ListaIndicadorAperturasSemana
            Me.ListaIndicadorAperturasCompletadasSemana = ListaIndicadorAperturasCompletadasSemana
            Me.ListarAperturasCompletadasPorUsuario = ListarAperturasCompletadasPorUsuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DiseñoIndicadoresPreprensasRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public IdPizarraInterno As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public NroLegalOrdenTrabajo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public NombreCliente As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public NombreProducto As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public FechaEnviadoCliche As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public TotalTrabajos As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public TotalTrabajosAño As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public TotalTrabajosmes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public TotalTrabajosdia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public FechaEnviadoClichemes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public Año As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public mes As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public NumeroSemana As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=13)>  _
        Public FechaIniSemEnviadoProceso As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=14)>  _
        Public FechaFinSemEnviadoProceso As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=15)>  _
        Public PromedioSem As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=16)>  _
        Public TrabajosSinCompletar As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=17)>  _
        Public FechaEnviadoProceso As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=18)>  _
        Public DescripcionFecha As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=19)>  _
        Public EstadoTrabajo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=20)>  _
        Public FechaIniSemEnviadoCliche As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=21)>  _
        Public FechaFinSemEnviadoCliche As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=22)>  _
        Public TiempoPreprensa As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=23)>  _
        Public TiempoPromedio As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=24)>  _
        Public IdEventoControl As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=25)>  _
        Public TrabajosConPC As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=26)>  _
        Public TrabajosSinPC As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal IdPizarraInterno As String,  _
                    ByVal NroLegalOrdenTrabajo As String,  _
                    ByVal NombreCliente As String,  _
                    ByVal NombreProducto As String,  _
                    ByVal FechaEnviadoCliche As Date,  _
                    ByVal TotalTrabajos As String,  _
                    ByVal TotalTrabajosAño As String,  _
                    ByVal TotalTrabajosmes As String,  _
                    ByVal TotalTrabajosdia As String,  _
                    ByVal FechaEnviadoClichemes As String,  _
                    ByVal Año As String,  _
                    ByVal mes As String,  _
                    ByVal NumeroSemana As String,  _
                    ByVal FechaIniSemEnviadoProceso As Date,  _
                    ByVal FechaFinSemEnviadoProceso As Date,  _
                    ByVal PromedioSem As String,  _
                    ByVal TrabajosSinCompletar As String,  _
                    ByVal FechaEnviadoProceso As Date,  _
                    ByVal DescripcionFecha As String,  _
                    ByVal EstadoTrabajo As String,  _
                    ByVal FechaIniSemEnviadoCliche As Date,  _
                    ByVal FechaFinSemEnviadoCliche As Date,  _
                    ByVal TiempoPreprensa As Integer,  _
                    ByVal TiempoPromedio As String,  _
                    ByVal IdEventoControl As String,  _
                    ByVal TrabajosConPC As String,  _
                    ByVal TrabajosSinPC As String)
            MyBase.New
            Me.IdPizarraInterno = IdPizarraInterno
            Me.NroLegalOrdenTrabajo = NroLegalOrdenTrabajo
            Me.NombreCliente = NombreCliente
            Me.NombreProducto = NombreProducto
            Me.FechaEnviadoCliche = FechaEnviadoCliche
            Me.TotalTrabajos = TotalTrabajos
            Me.TotalTrabajosAño = TotalTrabajosAño
            Me.TotalTrabajosmes = TotalTrabajosmes
            Me.TotalTrabajosdia = TotalTrabajosdia
            Me.FechaEnviadoClichemes = FechaEnviadoClichemes
            Me.Año = Año
            Me.mes = mes
            Me.NumeroSemana = NumeroSemana
            Me.FechaIniSemEnviadoProceso = FechaIniSemEnviadoProceso
            Me.FechaFinSemEnviadoProceso = FechaFinSemEnviadoProceso
            Me.PromedioSem = PromedioSem
            Me.TrabajosSinCompletar = TrabajosSinCompletar
            Me.FechaEnviadoProceso = FechaEnviadoProceso
            Me.DescripcionFecha = DescripcionFecha
            Me.EstadoTrabajo = EstadoTrabajo
            Me.FechaIniSemEnviadoCliche = FechaIniSemEnviadoCliche
            Me.FechaFinSemEnviadoCliche = FechaFinSemEnviadoCliche
            Me.TiempoPreprensa = TiempoPreprensa
            Me.TiempoPromedio = TiempoPromedio
            Me.IdEventoControl = IdEventoControl
            Me.TrabajosConPC = TrabajosConPC
            Me.TrabajosSinPC = TrabajosSinPC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DiseñoIndicadoresPreprensasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As DisenoIndicadoresService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListaIndicadorPreprensasDia() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public ListaIndicadorPreprensasDiaCliente() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public ListaIndicadorPreprensasDiaDetalle() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public ListaIndicadorPreprensasSemana() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public ListaIndicadorPreprensasCompletadasSemana() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public ListaIndicadorPreprensasDiaPruebaColor() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As DisenoIndicadoresService.BaseErrorEL, ByVal ListaIndicadorPreprensasDia() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL, ByVal ListaIndicadorPreprensasDiaCliente() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL, ByVal ListaIndicadorPreprensasDiaDetalle() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL, ByVal ListaIndicadorPreprensasSemana() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL, ByVal ListaIndicadorPreprensasCompletadasSemana() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL, ByVal ListaIndicadorPreprensasDiaPruebaColor() As DisenoIndicadoresService.DiseñoIndicadoresPreprensasEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListaIndicadorPreprensasDia = ListaIndicadorPreprensasDia
            Me.ListaIndicadorPreprensasDiaCliente = ListaIndicadorPreprensasDiaCliente
            Me.ListaIndicadorPreprensasDiaDetalle = ListaIndicadorPreprensasDiaDetalle
            Me.ListaIndicadorPreprensasSemana = ListaIndicadorPreprensasSemana
            Me.ListaIndicadorPreprensasCompletadasSemana = ListaIndicadorPreprensasCompletadasSemana
            Me.ListaIndicadorPreprensasDiaPruebaColor = ListaIndicadorPreprensasDiaPruebaColor
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IDiseñoIndicadoresChannel
        Inherits DisenoIndicadoresService.IDiseñoIndicadores, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DiseñoIndicadoresClient
        Inherits System.ServiceModel.ClientBase(Of DisenoIndicadoresService.IDiseñoIndicadores)
        Implements DisenoIndicadoresService.IDiseñoIndicadores
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListarAperturasDia(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarAperturasDia
            Return MyBase.Channel.ListarAperturasDia(request)
        End Function
        
        Public Function ListarAperturasCompletadasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarAperturasCompletadasSemana
            Return MyBase.Channel.ListarAperturasCompletadasSemana(request)
        End Function
        
        Public Function ListarAperturasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarAperturasSemana
            Return MyBase.Channel.ListarAperturasSemana(request)
        End Function
        
        Public Function ListarAperturasDiaDetalle(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarAperturasDiaDetalle
            Return MyBase.Channel.ListarAperturasDiaDetalle(request)
        End Function
        
        Public Function ListarAperturasCompletadasPorUsuario(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresAperturaRequest) As DisenoIndicadoresService.DiseñoIndicadoresAperturaResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarAperturasCompletadasPorUsuario
            Return MyBase.Channel.ListarAperturasCompletadasPorUsuario(request)
        End Function
        
        Public Function ListarPrepensaDia(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarPrepensaDia
            Return MyBase.Channel.ListarPrepensaDia(request)
        End Function
        
        Public Function ListarPreprensaDiaDetalle(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarPreprensaDiaDetalle
            Return MyBase.Channel.ListarPreprensaDiaDetalle(request)
        End Function
        
        Public Function ListarPreprensasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarPreprensasSemana
            Return MyBase.Channel.ListarPreprensasSemana(request)
        End Function
        
        Public Function ListarPreprensasCompletadasSemana(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarPreprensasCompletadasSemana
            Return MyBase.Channel.ListarPreprensasCompletadasSemana(request)
        End Function
        
        Public Function ListarPrepensaDiaPruebaColor(ByVal request As DisenoIndicadoresService.DiseñoIndicadoresPreprensasRequest) As DisenoIndicadoresService.DiseñoIndicadoresPreprensasResponse Implements DisenoIndicadoresService.IDiseñoIndicadores.ListarPrepensaDiaPruebaColor
            Return MyBase.Channel.ListarPrepensaDiaPruebaColor(request)
        End Function
    End Class
End Namespace
