'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class GeneralResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resinplast.Indicadores.Web.GeneralResource", GetType(GeneralResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carga cancelada.
        '''</summary>
        Public Shared ReadOnly Property DictCancelUpload() As String
            Get
                Return ResourceManager.GetString("DictCancelUpload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esta seguro de cancelar esta carga?.
        '''</summary>
        Public Shared ReadOnly Property DictCancelUploadConfirmation() As String
            Get
                Return ResourceManager.GetString("DictCancelUploadConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arrastre archivos aquí para cargar.
        '''</summary>
        Public Shared ReadOnly Property DictDefaultMessage() As String
            Get
                Return ResourceManager.GetString("DictDefaultMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Su navegador no permite arrastras el archivo de carga.
        '''</summary>
        Public Shared ReadOnly Property DictFallbackMessage() As String
            Get
                Return ResourceManager.GetString("DictFallbackMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilice el formulario de reserva a continuación para cargar sus archivos como en los días anteriores..
        '''</summary>
        Public Shared ReadOnly Property DictFallbackText() As String
            Get
                Return ResourceManager.GetString("DictFallbackText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo es muy grande ({{filesize}}MB). Máximo tamaño: {{maxFilesize}}MB.
        '''</summary>
        Public Shared ReadOnly Property DictFileTooBig() As String
            Get
                Return ResourceManager.GetString("DictFileTooBig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No puede cargar archivos de este tipo.
        '''</summary>
        Public Shared ReadOnly Property DictInvalidFileType() As String
            Get
                Return ResourceManager.GetString("DictInvalidFileType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No puede cargar más archivos.
        '''</summary>
        Public Shared ReadOnly Property DictMaxFilesExceeded() As String
            Get
                Return ResourceManager.GetString("DictMaxFilesExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remover archivo.
        '''</summary>
        Public Shared ReadOnly Property DictRemoveFile() As String
            Get
                Return ResourceManager.GetString("DictRemoveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property DictRemoveFileConfirmation() As String
            Get
                Return ResourceManager.GetString("DictRemoveFileConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Servidor respondió con el código: {{statusCode}}.
        '''</summary>
        Public Shared ReadOnly Property DictResponseError() As String
            Get
                Return ResourceManager.GetString("DictResponseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abrir.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAbrirTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaAbrirTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activo.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaActivo() As String
            Get
                Return ResourceManager.GetString("EtiquetaActivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaActivos() As String
            Get
                Return ResourceManager.GetString("EtiquetaActivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAgregar() As String
            Get
                Return ResourceManager.GetString("EtiquetaAgregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Envio Nuevo.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAgregarEnvios() As String
            Get
                Return ResourceManager.GetString("EtiquetaAgregarEnvios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAnadir() As String
            Get
                Return ResourceManager.GetString("EtiquetaAnadir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir Registro.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAnadirTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaAnadirTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anterior.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAnterior() As String
            Get
                Return ResourceManager.GetString("EtiquetaAnterior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anular.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAnular() As String
            Get
                Return ResourceManager.GetString("EtiquetaAnular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anular Registro.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAnularTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaAnularTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asignar Stage.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAsignarStageTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaAsignarStageTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ASN.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAsnTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaAsnTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Atender.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaAtenderTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaAtenderTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cambiar Cuenta.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCambiarCuenta() As String
            Get
                Return ResourceManager.GetString("EtiquetaCambiarCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCancelarTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaCancelarTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargar LPN.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCargarLpn() As String
            Get
                Return ResourceManager.GetString("EtiquetaCargarLpn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Centro de Distribución.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCentroDistribucion() As String
            Get
                Return ResourceManager.GetString("EtiquetaCentroDistribucion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCerrarTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaCerrarTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código de Barra.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCodigoBarra() As String
            Get
                Return ResourceManager.GetString("EtiquetaCodigoBarra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Código de Barra.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCodigoBarraEliminar() As String
            Get
                Return ResourceManager.GetString("EtiquetaCodigoBarraEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configurar Destino.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaConfiguracionReabastoDestino() As String
            Get
                Return ResourceManager.GetString("EtiquetaConfiguracionReabastoDestino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configurar Origen.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaConfiguracionReabastoOrigen() As String
            Get
                Return ResourceManager.GetString("EtiquetaConfiguracionReabastoOrigen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaConfirmar() As String
            Get
                Return ResourceManager.GetString("EtiquetaConfirmar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consultar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaConsultar() As String
            Get
                Return ResourceManager.GetString("EtiquetaConsultar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continuar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaContinuar() As String
            Get
                Return ResourceManager.GetString("EtiquetaContinuar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cambiar contraseña.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaContraseña() As String
            Get
                Return ResourceManager.GetString("EtiquetaContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Corto.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCorto() As String
            Get
                Return ResourceManager.GetString("EtiquetaCorto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar Corto.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCortoCancelar() As String
            Get
                Return ResourceManager.GetString("EtiquetaCortoCancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cuenta.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaCuenta() As String
            Get
                Return ResourceManager.GetString("EtiquetaCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Departamento.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDepartamento() As String
            Get
                Return ResourceManager.GetString("EtiquetaDepartamento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descargar LPN.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDescargarLpn() As String
            Get
                Return ResourceManager.GetString("EtiquetaDescargarLpn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desconectar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDesconectar() As String
            Get
                Return ResourceManager.GetString("EtiquetaDesconectar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desde.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDesde() As String
            Get
                Return ResourceManager.GetString("EtiquetaDesde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Despachar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDespacharTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaDespacharTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar Detalle.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDetalleAgregar() As String
            Get
                Return ResourceManager.GetString("EtiquetaDetalleAgregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Detalle.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDetalleEliminar() As String
            Get
                Return ResourceManager.GetString("EtiquetaDetalleEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle del Error:.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDetalleError() As String
            Get
                Return ResourceManager.GetString("EtiquetaDetalleError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reasignar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDetalleReasignar() As String
            Get
                Return ResourceManager.GetString("EtiquetaDetalleReasignar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDetalleTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaDetalleTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar Dirección.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDireccionEditar() As String
            Get
                Return ResourceManager.GetString("EtiquetaDireccionEditar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDireccionTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaDireccionTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distrito.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaDistrito() As String
            Get
                Return ResourceManager.GetString("EtiquetaDistrito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaEditar() As String
            Get
                Return ResourceManager.GetString("EtiquetaEditar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar Detalle.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaEditarDetalle() As String
            Get
                Return ResourceManager.GetString("EtiquetaEditarDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar Registro.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaEditarTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaEditarTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaEliminar() As String
            Get
                Return ResourceManager.GetString("EtiquetaEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Registro.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaEliminarTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaEliminarTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generar Envíos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaEnvioGenerar() As String
            Get
                Return ResourceManager.GetString("EtiquetaEnvioGenerar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Envío.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaEnvioTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaEnvioTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filas.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaFilas() As String
            Get
                Return ResourceManager.GetString("EtiquetaFilas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filas por Página.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaFilasPorPagina() As String
            Get
                Return ResourceManager.GetString("EtiquetaFilasPorPagina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filtros.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaFiltros() As String
            Get
                Return ResourceManager.GetString("EtiquetaFiltros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaGenerar() As String
            Get
                Return ResourceManager.GetString("EtiquetaGenerar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grabar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaGrabar() As String
            Get
                Return ResourceManager.GetString("EtiquetaGrabar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hasta.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaHasta() As String
            Get
                Return ResourceManager.GetString("EtiquetaHasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Huella.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaHuella() As String
            Get
                Return ResourceManager.GetString("EtiquetaHuella", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalle Huella.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaHuellaDetalle() As String
            Get
                Return ResourceManager.GetString("EtiquetaHuellaDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar Huella.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaHuellaEditar() As String
            Get
                Return ResourceManager.GetString("EtiquetaHuellaEditar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Huella.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaHuellaEliminar() As String
            Get
                Return ResourceManager.GetString("EtiquetaHuellaEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imprimir.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaImprimir() As String
            Get
                Return ResourceManager.GetString("EtiquetaImprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inactivo.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaInactivo() As String
            Get
                Return ResourceManager.GetString("EtiquetaInactivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inactivos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaInactivos() As String
            Get
                Return ResourceManager.GetString("EtiquetaInactivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liberación.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaLiberacion() As String
            Get
                Return ResourceManager.GetString("EtiquetaLiberacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Limpiar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaLimpiar() As String
            Get
                Return ResourceManager.GetString("EtiquetaLimpiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Margen Despacho.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaMargenDespacho() As String
            Get
                Return ResourceManager.GetString("EtiquetaMargenDespacho", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Margen Despacho Eliminar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaMargenDespachoEliminar() As String
            Get
                Return ResourceManager.GetString("EtiquetaMargenDespachoEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Usa.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaNoUsa() As String
            Get
                Return ResourceManager.GetString("EtiquetaNoUsa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nuevo.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaNuevo() As String
            Get
                Return ResourceManager.GetString("EtiquetaNuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nuevo Conteo.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaNuevoConteo() As String
            Get
                Return ResourceManager.GetString("EtiquetaNuevoConteo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Página.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaPagina() As String
            Get
                Return ResourceManager.GetString("EtiquetaPagina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provincia.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaProvincia() As String
            Get
                Return ResourceManager.GetString("EtiquetaProvincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reasignar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaReasignar() As String
            Get
                Return ResourceManager.GetString("EtiquetaReasignar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recepcionar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaRecepcionar() As String
            Get
                Return ResourceManager.GetString("EtiquetaRecepcionar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reimprimir.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaReimprimir() As String
            Get
                Return ResourceManager.GetString("EtiquetaReimprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaReporte() As String
            Get
                Return ResourceManager.GetString("EtiquetaReporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reportes.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaReportesTooltip() As String
            Get
                Return ResourceManager.GetString("EtiquetaReportesTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se encontraron registros para la búsqueda realizada..
        '''</summary>
        Public Shared ReadOnly Property EtiquetaResultadosBusquedaVacia() As String
            Get
                Return ResourceManager.GetString("EtiquetaResultadosBusquedaVacia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salir.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSalir() As String
            Get
                Return ResourceManager.GetString("EtiquetaSalir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSeleccionar() As String
            Get
                Return ResourceManager.GetString("EtiquetaSeleccionar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionar/Deseleccionar Todos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSeleccionarDeseleccionarTodos() As String
            Get
                Return ResourceManager.GetString("EtiquetaSeleccionarDeseleccionarTodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionar Motivos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSeleccionarMotivos() As String
            Get
                Return ResourceManager.GetString("EtiquetaSeleccionarMotivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionar Proveedor.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSeleccionarProveedor() As String
            Get
                Return ResourceManager.GetString("EtiquetaSeleccionarProveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionar Registro.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSeleccionarRegistro() As String
            Get
                Return ResourceManager.GetString("EtiquetaSeleccionarRegistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Todos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSeleccionTodos() As String
            Get
                Return ResourceManager.GetString("EtiquetaSeleccionTodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Siguiente.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSiguiente() As String
            Get
                Return ResourceManager.GetString("EtiquetaSiguiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suspendidos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaSuspendidos() As String
            Get
                Return ResourceManager.GetString("EtiquetaSuspendidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargar LPN&apos;s.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaTituloCargarLPN() As String
            Get
                Return ResourceManager.GetString("EtiquetaTituloCargarLPN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Todos.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaTodos() As String
            Get
                Return ResourceManager.GetString("EtiquetaTodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ubicación.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaUbicacion() As String
            Get
                Return ResourceManager.GetString("EtiquetaUbicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unidad de Medida.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaUnidadMedida() As String
            Get
                Return ResourceManager.GetString("EtiquetaUnidadMedida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Unidad de Medida.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaUnidadMedidaEliminar() As String
            Get
                Return ResourceManager.GetString("EtiquetaUnidadMedidaEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usa.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaUsa() As String
            Get
                Return ResourceManager.GetString("EtiquetaUsa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ver Envios.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaVerEnvios() As String
            Get
                Return ResourceManager.GetString("EtiquetaVerEnvios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visualizar.
        '''</summary>
        Public Shared ReadOnly Property EtiquetaVisualizar() As String
            Get
                Return ResourceManager.GetString("EtiquetaVisualizar", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
