'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class MessageResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resinplast.Indicadores.Web.MessageResource", GetType(MessageResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Advertencia.
        '''</summary>
        Public Shared ReadOnly Property Advertencia() As String
            Get
                Return ResourceManager.GetString("Advertencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro de realizar la acción?.
        '''</summary>
        Public Shared ReadOnly Property Confirmacion() As String
            Get
                Return ResourceManager.GetString("Confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro de grabar los cambios solicitados?.
        '''</summary>
        Public Shared ReadOnly Property ConfirmacionGuardar() As String
            Get
                Return ResourceManager.GetString("ConfirmacionGuardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se ejecuto ningun proceso..
        '''</summary>
        Public Shared ReadOnly Property EjecutoNingunProceso() As String
            Get
                Return ResourceManager.GetString("EjecutoNingunProceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se produjo un error al grabar el registro..
        '''</summary>
        Public Shared ReadOnly Property ErroralGrabar() As String
            Get
                Return ResourceManager.GetString("ErroralGrabar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Model de la Vista no definido.
        '''</summary>
        Public Shared ReadOnly Property ErrorCargarViewModel() As String
            Get
                Return ResourceManager.GetString("ErrorCargarViewModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe ingresar la Hora Fin.
        '''</summary>
        Public Shared ReadOnly Property ErrorHoraFin() As String
            Get
                Return ResourceManager.GetString("ErrorHoraFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe ingresar la Hora Inicio.
        '''</summary>
        Public Shared ReadOnly Property ErrorHoraInicio() As String
            Get
                Return ResourceManager.GetString("ErrorHoraInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oops....
        '''</summary>
        Public Shared ReadOnly Property ErrorMessage() As String
            Get
                Return ResourceManager.GetString("ErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exito.
        '''</summary>
        Public Shared ReadOnly Property Exito() As String
            Get
                Return ResourceManager.GetString("Exito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hora Fin.
        '''</summary>
        Public Shared ReadOnly Property HoraFin() As String
            Get
                Return ResourceManager.GetString("HoraFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hora Inicio.
        '''</summary>
        Public Shared ReadOnly Property HoraInicio() As String
            Get
                Return ResourceManager.GetString("HoraInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información.
        '''</summary>
        Public Shared ReadOnly Property Informacion() As String
            Get
                Return ResourceManager.GetString("Informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NO.
        '''</summary>
        Public Shared ReadOnly Property NO() As String
            Get
                Return ResourceManager.GetString("NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rango de Horas.
        '''</summary>
        Public Shared ReadOnly Property RangoHoras() As String
            Get
                Return ResourceManager.GetString("RangoHoras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se anuló registro con éxito..
        '''</summary>
        Public Shared ReadOnly Property SeAnuloExito() As String
            Get
                Return ResourceManager.GetString("SeAnuloExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se canceló registro con éxito..
        '''</summary>
        Public Shared ReadOnly Property SeCanceloExito() As String
            Get
                Return ResourceManager.GetString("SeCanceloExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se eliminó registro con éxito..
        '''</summary>
        Public Shared ReadOnly Property SeEliminoExito() As String
            Get
                Return ResourceManager.GetString("SeEliminoExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se guardó la información con éxito..
        '''</summary>
        Public Shared ReadOnly Property SeGuardoInformacionExito() As String
            Get
                Return ResourceManager.GetString("SeGuardoInformacionExito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SI.
        '''</summary>
        Public Shared ReadOnly Property SI() As String
            Get
                Return ResourceManager.GetString("SI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, debe ingresar.
        '''</summary>
        Public Shared ReadOnly Property ValidacionDebeIngresar() As String
            Get
                Return ResourceManager.GetString("ValidacionDebeIngresar", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
