'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SeguridadService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:resinplast:seguridad:autenticacion", ConfigurationName:="SeguridadService.IAutenticacion")>  _
    Public Interface IAutenticacion
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:seguridad:autenticacion:ListarPermisos", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarPermisos(ByVal request As SeguridadService.AutenticacionRequest) As SeguridadService.AutenticacionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:seguridad:autenticacion:ListarUsuarioPermisos", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ListarUsuarioPermisos(ByVal request As SeguridadService.AutenticacionRequest) As SeguridadService.AutenticacionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:resinplast:seguridad:autenticacion:ActualizarContrasena", ReplyAction:=""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(BaseEL))>  _
        Function ActualizarContrasena(ByVal request As SeguridadService.UsuariosRequest) As SeguridadService.UsuariosResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BaseErrorEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private descripcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("Codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(UsuariosEL)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BaseEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private flagEstadoField As Integer
        
        Private usuarioCreacionField As String
        
        Private fechaCreacionField As Date
        
        Private usuarioModificacionField As String
        
        Private fechaModificacionField As Date
        
        Private usuarioEliminacionField As String
        
        Private fechaEliminacionField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property FlagEstado() As Integer
            Get
                Return Me.flagEstadoField
            End Get
            Set
                Me.flagEstadoField = value
                Me.RaisePropertyChanged("FlagEstado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property UsuarioCreacion() As String
            Get
                Return Me.usuarioCreacionField
            End Get
            Set
                Me.usuarioCreacionField = value
                Me.RaisePropertyChanged("UsuarioCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property FechaCreacion() As Date
            Get
                Return Me.fechaCreacionField
            End Get
            Set
                Me.fechaCreacionField = value
                Me.RaisePropertyChanged("FechaCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property UsuarioModificacion() As String
            Get
                Return Me.usuarioModificacionField
            End Get
            Set
                Me.usuarioModificacionField = value
                Me.RaisePropertyChanged("UsuarioModificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property FechaModificacion() As Date
            Get
                Return Me.fechaModificacionField
            End Get
            Set
                Me.fechaModificacionField = value
                Me.RaisePropertyChanged("FechaModificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property UsuarioEliminacion() As String
            Get
                Return Me.usuarioEliminacionField
            End Get
            Set
                Me.usuarioEliminacionField = value
                Me.RaisePropertyChanged("UsuarioEliminacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property FechaEliminacion() As Date
            Get
                Return Me.fechaEliminacionField
            End Get
            Set
                Me.fechaEliminacionField = value
                Me.RaisePropertyChanged("FechaEliminacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UsuariosEL
        Inherits BaseEL
        
        Private idUsuarioField As String
        
        Private contrasenaField As String
        
        Private nombreField As String
        
        Private apellidoField As String
        
        Private cargoField As String
        
        Private estadoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdUsuario() As String
            Get
                Return Me.idUsuarioField
            End Get
            Set
                Me.idUsuarioField = value
                Me.RaisePropertyChanged("IdUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
                Me.RaisePropertyChanged("Contrasena")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("Nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
                Me.RaisePropertyChanged("Apellido")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Cargo() As String
            Get
                Return Me.cargoField
            End Get
            Set
                Me.cargoField = value
                Me.RaisePropertyChanged("Cargo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EventoEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idSistemaField As String
        
        Private idAplicacionField As String
        
        Private idDocumentoField As String
        
        Private idEventoField As String
        
        Private eventoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdSistema() As String
            Get
                Return Me.idSistemaField
            End Get
            Set
                Me.idSistemaField = value
                Me.RaisePropertyChanged("IdSistema")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IdAplicacion() As String
            Get
                Return Me.idAplicacionField
            End Get
            Set
                Me.idAplicacionField = value
                Me.RaisePropertyChanged("IdAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property IdDocumento() As String
            Get
                Return Me.idDocumentoField
            End Get
            Set
                Me.idDocumentoField = value
                Me.RaisePropertyChanged("IdDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property IdEvento() As String
            Get
                Return Me.idEventoField
            End Get
            Set
                Me.idEventoField = value
                Me.RaisePropertyChanged("IdEvento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Evento() As String
            Get
                Return Me.eventoField
            End Get
            Set
                Me.eventoField = value
                Me.RaisePropertyChanged("Evento")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DocumentoPermisoEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idSistemaField As String
        
        Private idAplicacionField As String
        
        Private idDocumentoField As String
        
        Private documentoField As String
        
        Private listaEventosField() As EventoEL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdSistema() As String
            Get
                Return Me.idSistemaField
            End Get
            Set
                Me.idSistemaField = value
                Me.RaisePropertyChanged("IdSistema")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IdAplicacion() As String
            Get
                Return Me.idAplicacionField
            End Get
            Set
                Me.idAplicacionField = value
                Me.RaisePropertyChanged("IdAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property IdDocumento() As String
            Get
                Return Me.idDocumentoField
            End Get
            Set
                Me.idDocumentoField = value
                Me.RaisePropertyChanged("IdDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Documento() As String
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
                Me.RaisePropertyChanged("Documento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ListaEventos", Order:=4)>  _
        Public Property ListaEventos() As EventoEL()
            Get
                Return Me.listaEventosField
            End Get
            Set
                Me.listaEventosField = value
                Me.RaisePropertyChanged("ListaEventos")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AplicacionPermisoEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idSistemaField As String
        
        Private idAplicacionField As String
        
        Private aplicacionField As String
        
        Private listaDocumentosField() As DocumentoPermisoEL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdSistema() As String
            Get
                Return Me.idSistemaField
            End Get
            Set
                Me.idSistemaField = value
                Me.RaisePropertyChanged("IdSistema")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IdAplicacion() As String
            Get
                Return Me.idAplicacionField
            End Get
            Set
                Me.idAplicacionField = value
                Me.RaisePropertyChanged("IdAplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Aplicacion() As String
            Get
                Return Me.aplicacionField
            End Get
            Set
                Me.aplicacionField = value
                Me.RaisePropertyChanged("Aplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ListaDocumentos", Order:=3)>  _
        Public Property ListaDocumentos() As DocumentoPermisoEL()
            Get
                Return Me.listaDocumentosField
            End Get
            Set
                Me.listaDocumentosField = value
                Me.RaisePropertyChanged("ListaDocumentos")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutenticacionPermisoEL
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private flagAutentificacionField As Integer
        
        Private idSistemaField As String
        
        Private sistemaField As String
        
        Private bdConexionField As String
        
        Private comodin1Field As String
        
        Private comodin2Field As String
        
        Private comodin3Field As String
        
        Private idUsuarioField As String
        
        Private nombreField As String
        
        Private apellidoField As String
        
        Private listaAplicacionesField() As AplicacionPermisoEL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property FlagAutentificacion() As Integer
            Get
                Return Me.flagAutentificacionField
            End Get
            Set
                Me.flagAutentificacionField = value
                Me.RaisePropertyChanged("FlagAutentificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IdSistema() As String
            Get
                Return Me.idSistemaField
            End Get
            Set
                Me.idSistemaField = value
                Me.RaisePropertyChanged("IdSistema")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Sistema() As String
            Get
                Return Me.sistemaField
            End Get
            Set
                Me.sistemaField = value
                Me.RaisePropertyChanged("Sistema")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property BdConexion() As String
            Get
                Return Me.bdConexionField
            End Get
            Set
                Me.bdConexionField = value
                Me.RaisePropertyChanged("BdConexion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Comodin1() As String
            Get
                Return Me.comodin1Field
            End Get
            Set
                Me.comodin1Field = value
                Me.RaisePropertyChanged("Comodin1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Comodin2() As String
            Get
                Return Me.comodin2Field
            End Get
            Set
                Me.comodin2Field = value
                Me.RaisePropertyChanged("Comodin2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Comodin3() As String
            Get
                Return Me.comodin3Field
            End Get
            Set
                Me.comodin3Field = value
                Me.RaisePropertyChanged("Comodin3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property IdUsuario() As String
            Get
                Return Me.idUsuarioField
            End Get
            Set
                Me.idUsuarioField = value
                Me.RaisePropertyChanged("IdUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("Nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property Apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
                Me.RaisePropertyChanged("Apellido")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ListaAplicaciones", Order:=10)>  _
        Public Property ListaAplicaciones() As AplicacionPermisoEL()
            Get
                Return Me.listaAplicacionesField
            End Get
            Set
                Me.listaAplicacionesField = value
                Me.RaisePropertyChanged("ListaAplicaciones")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AutenticacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public IdSistema As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public IdAplicacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public IdUsuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public Contrasena As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IdSistema As String, ByVal IdAplicacion As String, ByVal IdUsuario As String, ByVal Contrasena As String)
            MyBase.New
            Me.IdSistema = IdSistema
            Me.IdAplicacion = IdAplicacion
            Me.IdUsuario = IdUsuario
            Me.Contrasena = Contrasena
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AutenticacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As SeguridadService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListaPermisos() As SeguridadService.AutenticacionPermisoEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As SeguridadService.BaseErrorEL, ByVal ListaPermisos() As SeguridadService.AutenticacionPermisoEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListaPermisos = ListaPermisos
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsuariosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public FechaCreacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public FechaEliminacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public FechaModificacion As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public FlagEstado As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public UsuarioCreacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public UsuarioEliminacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public UsuarioModificacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public IdUsuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=8)>  _
        Public Contrasena As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=9)>  _
        Public Nombre As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=10)>  _
        Public Apellido As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=11)>  _
        Public Cargo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=12)>  _
        Public Estado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FechaCreacion As Date, ByVal FechaEliminacion As Date, ByVal FechaModificacion As Date, ByVal FlagEstado As Integer, ByVal UsuarioCreacion As String, ByVal UsuarioEliminacion As String, ByVal UsuarioModificacion As String, ByVal IdUsuario As String, ByVal Contrasena As String, ByVal Nombre As String, ByVal Apellido As String, ByVal Cargo As String, ByVal Estado As String)
            MyBase.New
            Me.FechaCreacion = FechaCreacion
            Me.FechaEliminacion = FechaEliminacion
            Me.FechaModificacion = FechaModificacion
            Me.FlagEstado = FlagEstado
            Me.UsuarioCreacion = UsuarioCreacion
            Me.UsuarioEliminacion = UsuarioEliminacion
            Me.UsuarioModificacion = UsuarioModificacion
            Me.IdUsuario = IdUsuario
            Me.Contrasena = Contrasena
            Me.Nombre = Nombre
            Me.Apellido = Apellido
            Me.Cargo = Cargo
            Me.Estado = Estado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsuariosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public CodigoError As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public DescripcionError As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public ListaError() As SeguridadService.BaseErrorEL
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public ListarUsuarios() As SeguridadService.UsuariosEL
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CodigoError As Integer, ByVal DescripcionError As String, ByVal ListaError() As SeguridadService.BaseErrorEL, ByVal ListarUsuarios() As SeguridadService.UsuariosEL)
            MyBase.New
            Me.CodigoError = CodigoError
            Me.DescripcionError = DescripcionError
            Me.ListaError = ListaError
            Me.ListarUsuarios = ListarUsuarios
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAutenticacionChannel
        Inherits SeguridadService.IAutenticacion, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AutenticacionClient
        Inherits System.ServiceModel.ClientBase(Of SeguridadService.IAutenticacion)
        Implements SeguridadService.IAutenticacion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListarPermisos(ByVal request As SeguridadService.AutenticacionRequest) As SeguridadService.AutenticacionResponse Implements SeguridadService.IAutenticacion.ListarPermisos
            Return MyBase.Channel.ListarPermisos(request)
        End Function
        
        Public Function ListarUsuarioPermisos(ByVal request As SeguridadService.AutenticacionRequest) As SeguridadService.AutenticacionResponse Implements SeguridadService.IAutenticacion.ListarUsuarioPermisos
            Return MyBase.Channel.ListarUsuarioPermisos(request)
        End Function
        
        Public Function ActualizarContrasena(ByVal request As SeguridadService.UsuariosRequest) As SeguridadService.UsuariosResponse Implements SeguridadService.IAutenticacion.ActualizarContrasena
            Return MyBase.Channel.ActualizarContrasena(request)
        End Function
    End Class
End Namespace
